# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-17 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20190313_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='province',
            field=models.CharField(default='', max_length=100, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='userfav',
            name='goods',
            field=models.ForeignKey(help_text='商品id', on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='userleavingmessage',
            name='file',
            field=models.FileField(blank=True, upload_to='', verbose_name='上传的文件'),
        ),
        migrations.AlterField(
            model_name='userleavingmessage',
            name='message',
            field=models.TextField(default='', help_text='留言内容', verbose_name='留言内容'),
        ),
        migrations.AlterField(
            model_name='userleavingmessage',
            name='subject',
            field=models.CharField(default='', help_text='主题', max_length=100, verbose_name='主题'),
        ),
    ]
